// Create Blog request
export const CREATE_BLOG_REQUEST="CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS="CREATE_BLOG_REQUEST";
export const CREATE_BLOG_ERROR="CREATE_BLOG_ERROR";


// Get Single Blog Request
export const GET_SINGLE_BLOG_REQUEST="GET_SINGLE_BLOG_REQUEST";
export const GET_SINGLE_BLOG_SUCCESS="GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_ERROR="GET_SINGLE_BLOG_ERROR";


// Get All Blogs Request
export const GET_ALL_BLOG_REQUEST="GET_ALL_BLOG_REQUEST";
export const GET_ALL_BLOG_SUCCESS="GET_ALL_BLOG_SUCCESS";
export const GET_ALL_BLOG_ERROR="GET_ALL_BLOG_ERROR";
